[package]
name = "hok-lottery-actix"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.4"
dotenvy = "0.15"
env_logger = "0.10"
mysql = "24.0.0"
log = "0.4.20"
serde = "1.0.192"
chrono = { version = "0.4", features = ["serde"] }
derive_more = "0.99.17"
